### ISSUE TITLE
Publishing messages to GCP Pub/Sub not working.

### ISSUE THREAD

**Issue by andyoll** [akka/alpakka#426] opened 2017-07-27 17:01 UTC
Example code to publish messages in https://github.com/akka/alpakka/blob/master/google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/ExampleUsage.scala does not work.
No messages are published.
OAuth access token is created ok, But HTTP request to publish a message results in a 400 response:
` {"code":400,
"message":"API key not valid. Please pass a valid API key.",
"status":"INVALID_ARGUMENT",...`

The apikey parameter defined here is redundant:
https://github.com/akka/alpakka/blob/master/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala#L105

I will submit a PR with this redundant request parameter removed.

**Comment by andyoll** [comment] 2017-07-27 17:12
please consider this pull request: https://github.com/akka/alpakka/pull/427

**Comment by ennru** [comment] 2018-01-08 09:38
PR #427 was merged loong time ago. Please re-open or add new ticket in case the issue is still relevant.

**Closed by ennru** 2018-01-08 09:38 UTC
Labels: p:google-cloud-pub-sub
