### ISSUE TITLE
alpakka-s3: AuthorizationHeaderMalformed: The authorization header is malformed; Invalid credential date. Date is not the same as X-Amz-Date

### ISSUE THREAD

**Issue by relgames** [akka/alpakka#1694] opened 2019-05-12 13:21 UTC
### Versions used 

Akka version: 2.5.22
Akka Http: 10.1.8
Alpakka-s3: 0.19

### Expected Behavior

S3Client.multipartUpload works with non-UTC timezone.

### Actual Behavior

For Amsterdam time zone, S3Client.multipartUpload fails with S3 error:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AuthorizationHeaderMalformed</Code>
    <Message>The authorization header is malformed; Invalid credential date. Date is not the same as X-Amz-Date.
    </Message>
    <RequestId>xxx</RequestId>
<HostId>yyy</HostId>
</Error>
```

It happens when current time zone is not UTC, and only if UTC date is different from date of the current time zone. For example, for Amsterdam time zone, current time is already `12-05-2019 01:00` but UTC time is `11-05-2019 23:00`.

If I use `-Duser.timezone=UTC` it works. Most probably, something is not right with timezones in `Signer.signedRequest`

**Comment by ennru** [comment] 2019-05-13 00:44
Duplicate of #1690

**Closed by ennru** 2019-05-13 00:44 UTC
Labels: p:aws-s3
