### ISSUE TITLE
S3: Support for v1 list-bucket

### ISSUE THREAD

**Issue by smarkey** [akka/alpakka#468] opened 2017-09-15 10:55 UTC
The S3 v1 list-bucket is not currently supported by Alpakka. I would like to introduce it so that I can use [S3Proxy](https://github.com/andrewgaul/s3proxy)

**Comment by johanandren** [comment] 2017-09-15 11:56
Duplicate of #192 ?

**Comment by smarkey** [comment] 2017-09-15 12:32
I don't believe so, this is for v1 support specifically rather than the v2 support already implemented.

**Comment by johanandren** [comment] 2017-09-15 14:00
Ah, thanks for clarifying

**Comment by francisdb** [comment] 2017-09-27 20:47
you might rather want to push for S3Proxy to support v2 listings?
https://github.com/andrewgaul/s3proxy/issues/168

**Closed** 2018-03-27 19:34 UTC
Labels: p:aws-s3
