### ISSUE TITLE
AMQP: recovery problem after RabbitMQ restart

### ISSUE THREAD

**Issue by gorbenkoya** [akka/alpakka#1270] opened 2018-10-10 13:56 UTC
I have designed simple consumer which works fine for me. So I can put some messages into queue using RabbitMQ management UI and see corresponding log records "AMPQ message is consumed: [message]" in my service console output.
But when I simulate networking (connection error) issue by restarting RabbitMQ things became worse. Stream just dies silently and no exception is throw by AMPQ Source. 
Then when I try to put new messages in RabbitMQ management UI they are not consumed anymore because stream has died.
As the solution  I have tried to use RestartSource.withBackoff, but new issue appears. Source was restarted, but after this every 2nd message is not consumed, some messages just disappear. Moreover  I have noticed 2 active connections were shown in RabbitMQ Management UI instead of single connection which was displayed before RabbitMQ restart. So looks like old connection was not closed and some messages disappeared there.  I have tied to use .withAutomaticRecoveryEnabled(true) feature, but nothing changes. 
Guys, please see my consumer code 
[AMPQClientConsumer.scala.txt](https://github.com/akka/alpakka/files/2464926/AMPQClientConsumer.scala.txt)

Please advice.

**Comment by gorbenkoya** [comment] 2018-10-10 14:05
I have noticed that Alpakka Kafka connector has consumerControl.shutdown() method which definitelly terminate consumer and active connections, please see here https://doc.akka.io/docs/akka-stream-kafka/current/errorhandling.html
Could it be considered as possible solution in our case?

**Comment by gorbenkoya** [comment] 2018-10-10 14:31
So before RabbitMQ restart I see only 1 consumer, but after restart there are 2 consumers listed on RabbitMQ Management UI page, please see screen below
![screen shot 2018-10-10 at 5 28 47 pm](https://user-images.githubusercontent.com/3693835/46743691-4cd3e400-ccb2-11e8-9e6a-ea1bff4eaaa2.png)

**Comment by 2m** [comment] 2018-10-10 14:32
Interesting. Amqp connector has connection closing logic in the `postStop` lifecycle hook:

https://github.com/akka/alpakka/blob/d53b2c88fa43671eff4e8eb38e72df73721790c7/amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpConnectorLogic.scala#L72-L80

Maybe we are missing some call on `channel` or `connection` that would release resources.

**Comment by gorbenkoya** [comment] 2018-10-16 12:33
I have put 
    .withAutomaticRecoveryEnabled(false)
    .withTopologyRecoveryEnabled(false)
and issue gone for me

**Comment by juanjoDiaz** [comment] 2018-10-16 14:16
Thanks for testing. Just set the default to false until someone tackles the auto-recovery issue.

**Closed** 2018-10-24 19:38 UTC
Labels: p:amqp

**Comment by carstenlenz** [comment] 2018-11-14 16:03
Hey. I don't know where to put this - we ran into the same issue and at least know *why* this happens.

All Alpakka AMQP components use an implementation of the `AmqpConnectionProvider`
```scala
sealed trait AmqpConnectionProvider {
  def get: Connection
  def release(connection: Connection): Unit = if (connection.isOpen) connection.close()
}
```
When a stream fails due to some (connection) error the Alpakka components will call the `AmpqConnectionProvider`s `release` method.

The `release` method does not work well with RabbitMQs `AutorecoveringConnection` which will be created by the the RabbitMQ connection factory when having `automaticRecovery` set to true which is (currently) the default:

An `AutorecoveringConnection` will response with `false` to `.isOpen()` when the underlying connection has failed for some reason (connection issue etc). So `release` will *not* call `close()` on it. That means the `AutorecoveringConnection` will recover the failed connection regardless of it being 'released' by Alpakka AMQP. This will effectively leak the connection. 

As we are using a `RestartSource` (just like in the initial issue) a new connection gets spawned by the `AmpqConnectionProvider`.

I cannot yet see a nice way to make use of the autorecovery feature of RabbitMQ in Alpakka AMQP as it is a quite low level error mitigation mechanism and Alpakka (and Streams in general) use more high level failure handling mechanisms.

**Comment by gorbenkoya** [comment] 2018-11-14 16:45
I have following setup which works fine for me
`  val decider: Supervision.Decider = {
    _ => Supervision.Stop
  }

  implicit val actorMaterializer = ActorMaterializer(ActorMaterializerSettings(system).withSupervisionStrategy(decider))
  private val queueDeclaration = QueueDeclaration(queueName).withDurable(true)
  private val connectionProvider = AmqpDetailsConnectionProvider(host, port)
    .withCredentials(AmqpCredentials(username, password))
    .withAutomaticRecoveryEnabled(false)
    .withTopologyRecoveryEnabled(false)

  private val source = RestartSource.withBackoff[IncomingMessage](
    minBackoff = 5.seconds,
    maxBackoff = 30.seconds,
    randomFactor = 0.2,
    maxRestarts = 20) { () =>
      AmqpSource.atMostOnceSource(
        NamedQueueSourceSettings(connectionProvider, queueName).withDeclaration(queueDeclaration), bufferSize = 100)
    }
`

**Comment by juanjoDiaz** [comment] 2018-11-14 21:49
Hi @carstenlenz ,

As @gorbenkoya mentioned. For now, the solutions is to disable the automatic recovery:
```scala
.withAutomaticRecoveryEnabled(false)
.withTopologyRecoveryEnabled(false)
```

from the next release, they'll be disabled by default.

**Comment by carstenlenz** [comment] 2018-11-15 10:53
Thanks. 
I just wanted to report the cause for the multiple connections as it seemed to be unknown.
We also have disabled automaticRecovery and that works for us. 
A possible fix for the multiple connection issue would be to always call `connection.close` if the connection is a `AutorecoveringConnection`.

**Comment by lukaszlenart** [comment] 2021-03-11 09:23
I was hit by the same problem, could you at least add a note to the docs about this problem? It would be nice to see some reference to this issue from here https://doc.akka.io/docs/alpakka/current/amqp.html#connecting-to-server

**Comment by mgargas** [comment] 2023-01-16 13:15
I am using alpakka 3.0.4. In this version, AmqpDetailsConnectionProvider has both automaticRecoveryEnabled and topologyRecoveryEnabled set to false be default. I looked up the object in debugger and indeed these two properties are set to false. Yet, I still experienced an issue of having 2 consumers when restarting a source. Do you have any suggestions on what also could cause this issue?
