### ISSUE TITLE
FAILED: AmqpConnectorsTest

### ISSUE THREAD

**Issue by jypma** [akka/alpakka#55] opened 2016-11-14 10:02 UTC
[TimeoutException](https://travis-ci.org/akka/alpakka/jobs/175643872#L728) on `AmqpConnectorsTest`, but only for Scala 2.12. Timing issues? That timeout already is at 10 seconds...
```
[error] Test akka.stream.alpakka.amqp.javadsl.AmqpConnectorsTest.publishFanoutAndConsume failed: java.util.concurrent.TimeoutException: null, took 10.326 sec

[error]     at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)

[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)

[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)

[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)

[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)

[error]     at scala.concurrent.package$.blocking(package.scala:123)

[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)

[error]     at akka.stream.alpakka.amqp.javadsl.AmqpConnectorsTest.publishFanoutAndConsume(AmqpConnectorsTest.java:142)
```

**Comment by stephennancekivell** [comment] 2016-11-23 07:32
I've noticed this as well, can we simply increase the timeout ?

**Comment by 2m** [comment] 2016-11-23 15:57
Looks like a duplicate of https://github.com/akka/alpakka/issues/20

**Closed** 2016-11-23 15:59 UTC
Labels: failed
