### ISSUE TITLE
Dynamo DB AWS SDK V2

### ISSUE THREAD

**Issue by ratoshniuk** [akka/alpakka#1475] opened 2019-02-01 10:50 UTC
Hi there, I am currently working on with Alpakka and found that aws SDK needs to be migrated to 2.3.*

Does anybody work with that? If no, I can do this

**Comment by ennru** [comment] 2019-02-01 11:13
Please, go ahead.

See #1345

**Comment by ratoshniuk** [comment] 2019-02-02 14:10
@ennru got it

**Comment by ennru** [comment] 2019-05-22 05:41
Duplicate of #1345.

**Closed by ennru** 2019-05-22 05:41 UTC
Labels: p:dynamodb
