### ISSUE TITLE
SQS: SqsAckSinkStage - RequeueWithDelay might need an explicit warning in documentation

### ISSUE THREAD

**Issue by nikitapecasa** [akka/alpakka#257] opened 2017-04-11 21:20 UTC
Hi,

Please help me understand idea behind `RequeueWithDelay`,
as I can see from [the code](https://github.com/akka/alpakka/blob/master/sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckSinkStage.scala#L71), it looks like it will only add a new message to the queue (if standard Amazon SQS queue is used), so after `RequeueWithDelay` I will have two messages with *identical body* and different message ids.
Therefore it means that `RequeueWithDelay` should be used with an extra caution, assuming default settings of Amazon SQS (Message Retention Period of 4 days and no dead letters enabled, i.e. 4 days of infinite retries and exploding unprocessed message count).

As an alternative to `RequeueWithDelay` one may consider to 
* [change message visibility timeout](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html), this will allow to postpone the retry of current message.
* Use FIFO queue instead of standard one, as only FIFO queues can use [ContentBasedDeduplication feature](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html), then it will be safe to send message with the same body

What do you think? Am I missing something in understanding of this SQS connector or documentation should be updated to reflect this case?

Side note: As user of RabbitMQ I was just a little bit confused with current semantic of `RequeueWithDelay` as in RabbitMQ there is a nack with requeue which puts message back into the queue instead of adding new message, so I thought that such documentation improvement may help others who had experience with RabbitMQ.

P.S.: Alpakka is a great library, I'm grateful to see it available in open source.

Regards,
Nikita.

**Comment by s12v** [comment] 2017-04-11 21:30
@nikitapecasa, good point

**Comment by s12v** [comment] 2017-04-12 10:59
@nikitapecasa, I think visibility timeout is a good option, I'll check it this weekend. FIFO SQS have some limitations (regions, throughput). Thanks!

**Comment by marco-hoyer** [comment] 2017-04-13 14:36
I'm not that sure why this is done at all. As we use SQS a message is either deleted after successful processing or reappears in the queue in case of an error without further action required by the application. So why should I resend a message to the queue when it will reappear by design?

**Comment by s12v** [comment] 2017-04-13 15:11
@marco-hoyer, as I understand, visibility timeout is for errors. When consumer crashes (or there's a network issue, etc.), you can try again. Usually, visibility timeout is small.

Sometimes you want to postpone messages and have control on this. Changing visibility timeout is actually a good idea, but then it can be affected by maximum receives, right?

Maybe this functionality is too much, I don't know. But we have something like this at work, I think it's useful.

**Comment by marco-hoyer** [comment] 2017-04-13 15:52
@s12v but from the queues perspective why should you differentiate an error from a consumer crash? In both cases a message has not been processed. SQS would make the message appear again after the visibility timeout and nothing is left on any error scenario. The way the SqsAckSinkStage handles thinks is that on an error the message is sent again and you have two messages in your queue. I see no advantage in this. In contrast I see a huge disadvantage. Even If your message processing is idempotent which makes it robust against duplicates you will have quite a lot of duplicate messages in your queue to be processed for no reason. Imagine your datastore fails and every message being processed is resent. There might be hundreds of thousands of duplicate messages for no reason.

**Comment by s12v** [comment] 2017-04-13 15:59
@marco-hoyer 
> but from the queues perspective why should you differentiate an error from a consumer crash

There's not much difference. You might want different behaviour in different situations.

> The way the SqsAckSinkStage handles thinks is that on an error the message is sent again and you have two messages in your queue. I see no advantage in this. In contrast I see a huge disadvantage

It's a bug. My bad :( I need to delete the message when requeue or use the visibility timeout.

**Comment by s12v** [comment] 2017-04-17 17:14
@nikitapecasa, @marco-hoyer, could you please take a look at my PR #270 ?

**Comment by nikitapecasa** [comment] 2017-05-02 14:25
@s12v The PR is LGTM, I have nothing to add, everything I thought of has been already mentioned in the comments. Thank you!

**Comment by solicode** [comment] 2017-07-06 08:50
I recently ran into the duplicate messages piling up issue described here. Even with idempotent requests, it puts a lot of unnecessary strain on the system.

I tried the branch with the proposed fix and confirmed that it solved the issue for me.

I'm curious, is there anything left blocking this from being merged?

**Comment by s12v** [comment] 2017-07-06 08:56
@solicode, actually, I only need to fix a test and it's done... I didn't have time due to a job change. Will look into it this week.

**Closed** 2017-07-18 12:52 UTC
Labels: api-change, p:sqs
