### ISSUE TITLE
AWS S3 S3Exception: The continuation token provided is incorrect

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka#339] opened 2017-06-14 14:58 UTC
When listing objects from a bucket in region `ap-southeast-2` we get the following error. For now we have not seen this on the other region we use.

```
[error] Exception in thread "main" akka.stream.alpakka.s3.S3Exception: The continuation token provided is incorrect
[error] 	at akka.stream.alpakka.s3.impl.S3Stream$$anonfun$akka$stream$alpakka$s3$impl$S3Stream$$entityForSuccess$1.apply(S3Stream.scala:256)
[error] 	at akka.stream.alpakka.s3.impl.S3Stream$$anonfun$akka$stream$alpakka$s3$impl$S3Stream$$entityForSuccess$1.apply(S3Stream.scala:255)
[error] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
[error] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
[error] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[error] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
[error] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
[error] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by Scalahansolo** [comment] 2017-06-14 15:02
This is a duplicate of #330 There already is fix pointed out.

**Closed** 2017-06-14 15:03 UTC
