### ISSUE TITLE
Failed: MqttFlowSpec mqtt server flow should receive a bidirectional connection and a subscription to a topic

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1549] opened 2019-03-01 11:43 UTC
```
[info] MqttFlowSpec:
[info] mqtt client flow
[info] - should establish a bidirectional connection and subscribe to a topic (488 milliseconds)
[info] mqtt server flow
[info] - should receive a bidirectional connection and a subscription to a topic *** FAILED *** (5 seconds, 131 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 51 times, sleeping 100000000 nanoseconds between each query. (MqttFlowSpec.scala:151)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at docs.scaladsl.MqttFlowSpec.$anonfun$new$4(MqttFlowSpec.scala:151)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

https://travis-ci.org/akka/alpakka/jobs/500172922

**Comment by huntc** [comment] 2019-03-01 11:59
Hmm. I thought I had fixed this... will have to look again.

**Comment by ennru** [comment] 2019-03-13 09:29
New failure for this test during `assertAllStagesStopped`.

https://travis-ci.org/akka/alpakka/jobs/505595719#L701

**Comment by 2m** [comment] 2019-05-28 17:25
https://travis-ci.com/akka/alpakka/jobs/203502744

**Comment by 2m** [comment] 2019-08-08 06:03
https://travis-ci.com/akka/alpakka/jobs/223291798

**Comment by seglo** [comment] 2019-10-19 15:07
Failure from PR #1981 build

https://travis-ci.org/akka/alpakka-kafka/jobs/599938923#L978

**Comment by ennru** [comment] 2019-12-13 07:33
https://travis-ci.com/akka/alpakka/jobs/266709851#L526 in #2006

**Comment by seglo** [comment] 2020-01-06 19:55
https://travis-ci.com/akka/alpakka/jobs/271383967#L673

**Comment by seglo** [comment] 2020-01-08 18:48
https://travis-ci.com/akka/alpakka/jobs/273581920#L700

**Comment by ennru** [comment] 2020-01-20 09:46
This keeps failing annoyingly often.
Hopefully the captured log can help to understand the cause
https://travis-ci.com/akka/alpakka/jobs/277511548#L452 in #2040

**Comment by raboof** [comment] 2020-02-14 15:08
https://travis-ci.com/akka/alpakka/builds/147336325

**Comment by raboof** [comment] 2020-02-14 15:08
https://travis-ci.com/akka/alpakka/jobs/283306085

**Comment by ennru** [comment] 2020-03-16 10:29
https://travis-ci.com/github/akka/alpakka/jobs/298331215#L709 in #2201

**Comment by raboof** [comment] 2020-03-17 10:10
(this failure also occurs for `TypedMqttFlowSpec`, e.g. https://travis-ci.com/github/akka/alpakka/jobs/298850833)

**Comment by ennru** [comment] 2020-03-17 11:54
This is expected to be fixed with #2207

**Comment by ennru** [comment] 2020-03-24 17:35
It shows again in #2227 

```
UntypedMqttFlowSpec:
mqtt server flow
- should receive a bidirectional connection and a subscription to a topic *** FAILED *** (5 seconds, 182 milliseconds)
  A timeout occurred waiting for a future to complete. Queried 51 times, sleeping 100000000 nanoseconds between each query. (MqttFlowSpec.scala:176)
  org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
  at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
  at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
  at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
  at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
  at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
  at docs.scaladsl.MqttFlowSpec.$anonfun$$init$$7(MqttFlowSpec.scala:176)
```

**Comment by ennru** [comment] 2020-04-28 11:48
Again in #2284 

https://travis-ci.com/github/akka/alpakka/jobs/324193080#L766

**Comment by ennru** [comment] 2020-04-28 11:50
And in #2285 

https://travis-ci.com/github/akka/alpakka/jobs/324197704#L559

**Comment by seglo** [comment] 2020-04-28 15:02
https://travis-ci.com/github/akka/alpakka/jobs/324283744

**Comment by seglo** [comment] 2020-09-14 14:08
https://travis-ci.com/github/akka/alpakka/jobs/383489151#L576

**Comment by ennru** [comment] 2020-09-21 08:14
https://travis-ci.com/github/akka/alpakka/jobs/387994230#L420

```
[info] TypedMqttFlowSpec:
[info] mqtt server flow
[info] - should receive a bidirectional connection and a subscription to a topic *** FAILED *** (5 seconds, 84 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Waited 5000000000 nanoseconds. (MqttFlowSpec.scala:176)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at docs.scaladsl.MqttFlowSpec.$anonfun$$init$$7(MqttFlowSpec.scala:176)
```

This continues to fail quite often. (Would you have time to take a look, @huntc?)

**Comment by ennru** [comment] 2020-09-23 06:26
https://travis-ci.com/github/akka/alpakka/jobs/389369053#L1190 in #2419

**Comment by ennru** [comment] 2020-10-05 12:08
In the logs, this message seems relevant to me. The test expects the `Publish`, but the `PublishReceivedLocally` wasn't handled.

```
[received] Element: Right(Event(SubAck(PacketId(1),Vector(ControlPacketFlags(2))),None))

Message [akka.stream.alpakka.mqtt.streaming.impl.ClientConnection$PublishReceivedLocally] 
to Actor[akka://TypedMqttFlowSpec/system/server-connector-2/client-connection-typed-flow-spec%2Fflow#-297118130] 
was unhandled. 
```

https://travis-ci.com/github/akka/alpakka/jobs/389369053#L1182

**Comment by ennru** [comment] 2020-10-05 14:20
It appears to me that https://github.com/akka/alpakka/pull/2189 might prevent this error. When I compare the order of events in the failures with what successful execution does, it looks like things get stuck when they arrive in a different order.

**Comment by raboof** [comment] 2020-10-19 11:33
https://travis-ci.com/github/akka/alpakka/jobs/401923963

**Comment by ennru** [comment] 2023-04-24 12:03
This test is reenabled as it was related to the wrong encoding of QoS levels which was fixed in
- #2969.

**Closed by ennru** 2023-04-24 12:03 UTC
Labels: failed, p:mqtt-streaming
